language: rust
cache: cargo
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade openssl; fi
matrix:
  include:
  - rust: nightly
    install:
    - cargo install rustfmt-nightly -f
    script:
    - cargo fmt -- --write-mode="diff"
  - os: linux
    dist: trusty
  - os: osx
    env:
    - OPENSSL_INCLUDE_DIR="`brew --prefix openssl`/include"
    - OPENSSL_LIB_DIR="`brew --prefix openssl`/lib"
    - DEP_OPENSSL_INCLUDE="`brew --prefix openssl`/include"
script:
- cargo build
- cargo test