[package]
name = "eco"
version = "0.1.2"
authors = [
    "bvssvni <bvssvni@gmail.com>"
]
keywords = ["piston", "ecosystem", "dependencies", "analysis"]
description = "A tool for reasoning about breaking changes in Rust ecosystems"
license = "MIT"
repository = "https://github.com/pistondevelopers/eco.git"
homepage = "https://github.com/pistondevelopers/eco"

[lib]
name = "eco"
path = "src/lib.rs"

[dependencies]
piston_meta = "0.12.1"
hyper = "0.6.9"
range = "0.1.1"
semver = "0.1.20"
